
import React, { useState } from 'react';
import { generateImageFromPrompt } from '../services/geminiService';
import Spinner from './Spinner';
import BackIcon from './icons/BackIcon';
import DownloadIcon from './icons/DownloadIcon';

interface ImageGeneratorProps {
    onBack: () => void;
}

const ImageGenerator: React.FC<ImageGeneratorProps> = ({ onBack }) => {
    const [prompt, setPrompt] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt) {
            setError('Please enter a prompt to generate an image.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedImageUrl(null);

        try {
            const imageUrl = await generateImageFromPrompt(prompt);
            setGeneratedImageUrl(imageUrl);
        } catch (err: any) {
            setError(err.message || 'An unexpected error occurred during image generation.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="bg-white p-6 sm:p-8 rounded-xl shadow-lg w-full max-w-2xl mx-auto">
            <div className="flex justify-between items-center mb-6">
                <button
                    onClick={onBack}
                    className="flex items-center gap-2 text-sm font-semibold text-gray-600 hover:text-gray-900 transition-colors"
                >
                    <BackIcon className="w-5 h-5" />
                    Back to Identifier
                </button>
            </div>
            
            <div className="flex flex-col gap-4">
                <label htmlFor="prompt-input" className="font-semibold text-gray-700">Enter a prompt for your image:</label>
                <textarea
                    id="prompt-input"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="e.g., A watercolor painting of a futuristic greenhouse on Mars"
                    className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-shadow duration-200"
                    rows={3}
                    disabled={isLoading}
                />
                <button
                    onClick={handleGenerate}
                    disabled={isLoading || !prompt}
                    className="w-full bg-green-600 hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-bold py-3 px-4 rounded-lg transition-colors text-base"
                >
                    {isLoading ? 'Generating...' : '✨ Generate Image'}
                </button>
            </div>

            <div className="flex items-center justify-center p-4 mt-4 min-h-[300px] bg-gray-50 rounded-lg border border-gray-200">
                {isLoading ? <Spinner /> :
                    error ? (
                        <div className="bg-red-100 border border-red-400 text-red-700 p-4 rounded-lg text-center w-full">
                            <h3 className="font-bold text-lg mb-2">Generation Failed</h3>
                            <p>{error}</p>
                        </div>
                    ) : generatedImageUrl ? (
                        <div className="text-center">
                            <img src={generatedImageUrl} alt="Generated by AI" className="max-w-full h-auto max-h-80 rounded-lg shadow-md mb-4"/>
                            <a 
                                href={generatedImageUrl} 
                                download={`ai-generated-${Date.now()}.png`}
                                className="inline-flex items-center gap-2 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-lg transition-colors text-sm"
                            >
                                <DownloadIcon className="w-4 h-4" />
                                Download Image
                            </a>
                        </div>
                    ) : (
                        <p className="text-gray-500">Your generated image will appear here.</p>
                    )
                }
            </div>
        </div>
    );
};

export default ImageGenerator;